stages:
- name: build
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/acs/maven
      shellScript: |-
        cd ./demo/demo
        mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ../demo/demo/Dockerfile
      buildContext: .
      tag: localhost:5000/demo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 106.13.149.36:5000
timeout: 60
notification: {}
