stages:
- name: build
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/acs/maven
      shellScript: |-
        cd ./demo
        mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./demo/Dockerfile
      tag: 17865923318/demo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
  - env:
      PLUGIN_DEBUG: true
      PLUGIN_INSECURE: true
timeout: 60
notification: {}
